version = "1.0"

[[agents]]
name = "SuperAgent"
description = "Agente Qodo con todas las capacidades habilitadas"
author = "S1R4X"
entrypoint = "qodo.md"
tools = ["git", "filesystem", "ripgrep", "web_search", "qodo_aware_context_retriever", "qodo_merge"]

[settings]
default_language = "es"
debug = true